### ISSUE TITLE
Adjust header level

### ISSUE THREAD

**Issue by bilke** [selvinortiz/craft.doxter#13]
Just a feature request:

It would be nice to adjust the starting header level. E.g. If I set the starting header level to 3 then the following markdown:

```markdown
# Header

## Subheader
```

would be outputted as:

```html
<h3>Header</h3>

<h4>Subheader</h4>
```

PS: Can you please also give an example on how to pass parameters to the `doxter`-filter?

Thanks!

**Comment by selvinortiz** [comment]
Hey @bilke,
Sorry for the delayed response!

I'm in the middle of a rewrite (backwards compatible) and will consider you request.

As far as using the `doxter` filter, you can basically look at the [Filter API](https://github.com/selvinortiz/craft.doxter#filter-api) to see what option are available and format it this way:

```twig
{{ "# Hello"|doxter({addHeaderAnchors: true, addHeaderAnchorsTo: [h1, h2, h3]}) }}
```

Hope that helps, if not, please let me know and I'll try to help however I can.

**Comment by bilke** [comment]
Thanks! Yes that helps!

**Comment by selvinortiz** [comment]
Hey @bilke, I'm looking into implementing this feature and I wanted your feedback.

Suppose that you set your `starting header level` to **3** and you set your `headers to parse` to `h1, h2, h3`

Given the following markdown...

```md
# Header 1
## Header 2
### Header 3
#### Header 4
##### Header 5
###### Header 6
```

Will the following output be generated or something else?

```html
<h3 id="#header-1">Header 1</h3>
<h4 id="#header-2">Header 2</h4>
<h5 id="#header-3">Header 3</h5>
<h6>Header 4</h6>
<h6>Header 5</h6>
<h6>Header 5</h6>
```

This is what I'm working towards with the new parsing algorithm that I'm writing, is this what you would expect to happen?

Your feedback is appreciated!

**Comment by bilke** [comment]
Yes, exactly! Thanks!

**Comment by selvinortiz** [comment]
That great.

I've got this on `dev` right now and plan on merging with `master` as soon as finish a writing a couple more tests and updating the documentation.

May I ask what version of `Doxter` you've got installed?
Just want to make sure you'll have a pretty easy upgrade path.
