### ISSUE TITLE
Allow Doxter toolbar to scroll with page

### ISSUE THREAD

**Issue by BenParizek** [selvinortiz/craft.doxter#15]
Doxter provides a handful of handy icons we can click on to insert elements and assets and such.

It would be nice if the toolbar scrolled with the page like the toolbar from the default Rich Text field.  For longer form content, it's easy to lose the toolbar while editing your content.

**Comment by selvinortiz** [comment]
Trying to do anything fancy with javascript in this context gets messy really quickly.

@BenParizek The best I can do right now is give you the option to place the toolbar at the `Top`, `Bottom`, or `Both` via the fieldtype settings.

I know it doesn't solve the problem but hopefully it helps in some way until I find a better way to do this.
