### ISSUE TITLE
php7 Compatibility (Only variables should be passed by reference)

### ISSUE THREAD

**Issue by pixeljitsu** [selvinortiz/craft.doxter#19]
DoxterService.php(340)

329     /**
330      * @param string $name
331      * @param array  $params
332      *
333      * @return bool
334      * @throws \CException
335      */
336     protected function raiseOwnEvent($name, array $params = array())
337     {
338         $event = new Event($this, $params);
339 
340         $this->raiseEvent(array_pop(explode('\\', $name)), $event);
341 
342         return $event->performAction;
343     }
344 }

**Comment by selvinortiz** [comment]
Should be an easy fix, I'll try to cut a new release this weekend if I get some time: )
