### ISSUE TITLE
Footnotes don't get the correct values when grouping fields

### ISSUE THREAD

**Issue by BenParizek** [selvinortiz/craft.doxter#20]
I have a Matrix field with several blocks. Some of those blocks are Doxter fields.  I am trying to loop through all of the blocks and create a master variable, and then run the doxter filter across all of my fields at once so that I can use footnotes and so that those footnotes appear at the bottom of the page.

I've updated Doxter to output raw text:

    {{ block.markdown.text()|raw }}

And this is an example of how I am adding all of my field output to an `articleBody` variable and then running a doxter filter over the whole variable.

    {% set articleBody %}
        {%- for block in entry.matrixField -%}
            {% include "_partials/blocks/" ~ block.type %}
        {%- endfor -%}
    {% endset %}

    {{ articleBody|doxter }}

When I do this, the footnotes appear and are linked properly.  The footnotes are even correctly numbered in the footer area.  But the footnote numbers in the body area are incorrect.

    Footnote in Body 1 [5]
    Footnote in Body 2 [6]
    
    ....
    
    Footnote Footer 1 [1]
    Footnote Footer 1 [2]

The numbers in the body change depending on the number of links I add to my body area.

| Number of links  | Numbers start at |
| ---------- |---- |
| 1 Link   | Footnotes in body start at number 3 |
| 2 Links | Footnotes in body start at 5 (5, 6) |
| 3 Links | Footnotes in body start at 6 (6, 7, 8) |
| 7 Links | Footnotes in body start at 7 (7, 8, 9, 10) |

I have looked into this a bit and am not sure what is going on.  It looks like Parsedown has a few open tickets regarding footnotes, so it may just be a bug in the Parsedown library.  I ran the same content through the `smartdown` filter of the Smartdown plugin and the footnotes worked properly.

**Comment by selvinortiz** [comment]
Hi @BenParizek 
Oh man, I thought I had replied to you about this a long time ago. I guess we may have discussed it over a hangout or something, and I never added an official response here.

Anyway, I'm running through some updates and saw this open issue.
You were right; I think it might be a problem with **Parsedown** itself.

If anything, it could be the header parsing that **Doxter** does to auto link headers.

Would you be able to provide the full markdown from all your blocks to see if I can run some tests?

I ran a bunch of tests on footnotes with a massive document and it all worked fine but I'd like to test exactly the way your testing so I can reproduce the issue.

**Comment by selvinortiz** [comment]
May not be a common enough issue to try to tackle, I'm gonna close this for now but feel free to reopen if you feel it still needs fixing.
