### ISSUE TITLE
Doxter plugin not working anymore

### ISSUE THREAD

**Issue by m-emelchenkov** [selvinortiz/craft.doxter#23]
Craft CMS 2.6.2780 (current version), the plugin can't render its editor anymore.

![untitled](https://cloud.githubusercontent.com/assets/7569252/14413297/d31fb10c-ff86-11e5-880c-23ef9db1be41.png)

**Comment by selvinortiz** [comment]
I remember getting a patch from P&T about this on 2.5 I believe. Are you seing this on the latest version of Doxter?

**Comment by m-emelchenkov** [comment]
Trunk version works like a charm, thanks! It's time to make a new release, I suppose (because I downloaded latest release which is not working anymore).

**Comment by selvinortiz** [comment]
Great, I'll cut a new release and publish that as soon as I get a chance. Thanks for the heads up.
