### ISSUE TITLE
Textarea missed :)

### ISSUE THREAD

**Issue by davidhellmann** [selvinortiz/craft.doxter#24]
I've installed doxter but there is no textarea there. Any Ideas?

<textarea class="text nicetext code doxter fullwidth" rows="2" cols="50" id="snippet" name="snippet"></textarea>

**Comment by gisu** [comment]
Maybe incompatible with the newest Craft Version.

**Comment by selvinortiz** [comment]
Might have to download the repo instead of the official release until I cut a new one.

See https://github.com/selvinortiz/craft.doxter/issues/23

**Comment by selvinortiz** [comment]
@davidhellmann Just cut a new official release to address this without cloning the trunk: https://github.com/selvinortiz/craft.doxter/releases/tag/v1.2.0
