### ISSUE TITLE
Toolbar for Reference Tags not behaving as expected with locales

### ISSUE THREAD

**Issue by chris-garner** [selvinortiz/craft.doxter#26]
When using the reference tag toolbar, it only seems to list entries enabled for the default locale - not the current locale (expected behaviour). I also checked the value of `Craft.locale` in the JS console and it returns the default locale, not the current one.

It would be great if this could be fixed as it's causing a bit of headache for our editors.

**Comment by selvinortiz** [comment]
Hi Chris, thanks for the report.

I'm currently trying to focus on a version of Doxter for Craft 3, but I will take a look and follow up with you.

**Comment by chris-garner** [comment]
Thanks - much appreciated.

**Comment by selvinortiz** [comment]
Hi @chris-garner,
After looking into this in more detail, I found out that Craft does not make things easier on the JS side of things. I'll try to implement a workaround if I can but it might be something that will have to wait till Craft 3. Sorry Chris!
