### ISSUE TITLE
Doxter messes up Craft's Plugins Page

### ISSUE THREAD

**Issue by alinnert** [selvinortiz/craft.doxter#27]
I'm using Craft 2.6.2950 and Doxter 1.3.0

After installing it messes up the Plugins page (When you go to "Settings" > "Plugins"). It looks like this:

![doxter-craft-cms](https://cloud.githubusercontent.com/assets/2638971/20095871/993bd6c4-a5a7-11e6-9ec9-9f3516db0d7e.png)

The Lightswitch Buttons aren't working on this page and the list of available plugins is missing.

The plugin itself is working fine, though. I can access the settings directly via "Settings" > "Doxter". Everything is working just fine there, too.

**Comment by selvinortiz** [comment]
Hi @alinnert, sorry for the delayed response.

I'll do some testing on my end and figure out what's going on.
Would you be able to tell what other plugins you have installed in case I need to test with those installed as well?

**Comment by alinnert** [comment]
Hi, no problem. It's the only plugin I have installed right now.

But now I can't reproduce it anymore. Craft is running on a self-made development environment (Debian in a VM). Maybe it's related to that.
Today evening I will try to setup a new site and install the plugin again and see what happens.

**Comment by alinnert** [comment]
Okay, it happened again on a clean Craft installation. But this is really strange.

- On the first page where I've noticed it, it doesn't happen anymore.
- I've setup a new fresh Craft installation. There this error happens again. But for a very short time, it went back to normal. But now the error is back.
- On a website that's in production this error doesn't occur at all.

The first two pages are running on the same server.

After enabled devMode I saw this error log: https://jsfiddle.net/alinnert/09xb0wxL/
(It's really hard to share big tables..)
Does this help you?

**Comment by selvinortiz** [comment]
@alinnert Got it, thank you.

Due to the inconsistency or the issue and the fact that it doesn't affect production, the issue may be with xdebug and the fact that is not allowing twig to render the whole template.

Can you take a look at this: https://craftcms.stackexchange.com/questions/1559/why-are-some-entry-detail-views-empty-in-the-control-panel

**Comment by alinnert** [comment]
Oh wow... This looks exactly like my problem. I've uninstalled xdebug for now and it works fine.
Thanks a lot.

I don't need xdebug for now. But I'll pay attention to version and settings the next time I'll give it a try.
