### ISSUE TITLE
Conflict with Typogrify

### ISSUE THREAD

**Issue by Emkaytoo** [selvinortiz/craft.doxter#29]
I have the [craft-typogrify plugin](https://github.com/jamiepittock/craft-typogrify) installed, and after installing Doxter in the CP, I get this error:

**Fatal error**: Cannot redeclare smarty_modifier_smartypants() (previously declared in path_to_project/dist/craft/plugins/doxter/common/parsedown/Typography.php:311) in path_to_project/dist/craft/plugins/typogrify/lib/smartypants.php on line 68

And now I can't even access the CP without deleting the files.

I'm a total n00b at PHP, but I think both are using the same framework or something. 

Any advice/workarounds?

**Comment by Emkaytoo** [comment]
I forgot: I found [this issue](https://github.com/jamiepittock/craft-typogrify/issues/4) in the craft-typogrify repo that I think is similar.

**Comment by selvinortiz** [comment]
Yeah, sounds like two plugins are attempting to use the same dependency and the same classes are being loaded in multiple places, causing the fatal error.

The only workaround would be to make sure that the files referenced in the error are only loaded from one of the plugins.

However, this is something that I'd like to look at and attempt to solve for Doxter.

**Comment by selvinortiz** [comment]
Moving this to Doxter for Craft 3
