### ISSUE TITLE
Deprecation error in Craft 3.0.0-RC17.1

### ISSUE THREAD

**Issue by AdamVig** [selvinortiz/craft.doxter#30]
```
Passing a string to ArrayHelper::toArray() has been deprectaed. Use StringHelper::split() instead.
```

**Comment by selvinortiz** [comment]
@AdamVig This repo if for the version of Doxter that targets Craft 2. Are you having this issue with the Doxter version for Craft 3? https://github.com/selvinortiz/craft-plugin-doxter

**Comment by AdamVig** [comment]
@selvinortiz My mistake, I was using the wrong version of the plugin. Thank you for your reply.
